export { default as Header } from './header/NavBar'
export { default as LoginHeader } from './forms/loginform/Login'
export { default as ContactHeader } from './forms/contactform/Contact'
export { default as RegisterHeader } from './forms/registerform/Register'
export { default as LandingHeader } from './landing/Landing'
export { default as Loader } from './loaders/Loading'
